#!/usr/bin/env python3
"""Emit the README status table from the committed manifests (Bucket 3).

Ritual owner (charter §3 document-ownership rule) of the README status
block: run this and paste its output. Every byte figure is computed from
config/targets/*.yaml here — never hand-typed (charter §5 proof-value rule).
Shows the full six-state split, matched never alone (config/README.md
reporting rule).

Usage: python3 tools/status_table.py
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from prg import load_manifests, segment_stats, SEGMENT_STATES

# column order: matched first, data last, others in between
COLS = ("matched", "attempted", "unattempted",
        "library-identified", "library-candidate", "data")


def main():
    print("<!-- generated by tools/status_table.py — do not hand-edit the "
          "numbers; rerun and paste (charter §5). -->")
    header = "| target | rebuild | " + " | ".join(COLS) + " |"
    sep = "|" + "---|" * (len(COLS) + 2)
    print(header)
    print(sep)
    for m in load_manifests():
        stats = segment_stats(m)
        size = m["size"]
        units = m.get("units") or {}
        nmatched = sum(1 for u in units.values() if u["status"] == "matched")
        cells = []
        for c in COLS:
            b = stats[c][1]
            cell = f"{b:,} B"
            if c == "matched" and b and nmatched:
                cell += f" ({nmatched} unit{'s' if nmatched != 1 else ''})"
            cells.append(cell)
        role = m.get("role", "?")
        print(f"| {m['target']} ({size:,} B) | {role} | " + " | ".join(cells) + " |")


if __name__ == "__main__":
    main()
